using UnityEngine;

public class Trap : MonoBehaviour
{
    [SerializeField] private float velocidad;
    [SerializeField] Vector3 direccionInicial;
    [SerializeField] float tiempoA;
    private Vector3 direcci贸nActual;
    private float timer;
    void Start()
    {
        direcci贸nActual = direccionInicial;
    }

    // Update is called once per frame
    void Update()
    {
        timer += Time.deltaTime;
        
        transform.Translate(direcci贸nActual * velocidad * Time.deltaTime);
        if (timer >= 2f)
        {
            direcci贸nActual *= -1; 
            timer = 0;
        }
       
    }     
}